title: "James Tombleson"
baseURL: "https://www.jamestombleson.com"
languageCode: "en-us"
theme: ["github.com/theNewDynamic/gohugo-theme-ananke"]

SectionPagesMenu: "main"
Paginate: 9
googleAnalytics: ""
enableRobotsTXT: true
enableEmoji: true

sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

params:
  text_color: ""
  author: "James Tombleson"
  favicon: ""
  site_logo: ""
  description: "Personal site"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class: "bg-black"
  recent_posts_number: 3

  ananke_socials:
    - name: github
      url: https://github.com/jtom38
    - name: rss
      url: index.xml

social:
  github: jtom38
  rss: